chromium: Update for 151.0.7922.47
The Debian Chromium source package now has a new orig-source tarball:
orig-pre-gen. This is the result of my efforts to address the ongoing
difficulties of building Chromium for Debian (old)stable and earlier
Ubuntu releases, due to the relatively recent build dependencies that
are needed to generate source files. At present, said build-deps are

* bindgen
* nodejs
* golang (new for 151)

These either need to be backported, or workarounds put in place that
allow the build to use the older versions that are available. And
that's a fair amount of work.

So I developed a "pre-gen" framework that saves the files that are
generated using these dependencies, running on Debian unstable, and
then re-uses them in the stable builds without needing to re-generate
same. Not only does this work swimmingly, it allows us to get rid of
aaaaall the compatibility hacks and workarounds for these dependencies
that were needed previously.

Which means, it's time to clean house!

Drop these patches, as we do not need to run bindgen anymore, nor a
version of Node.js newer than what jammy has (v12):

* bookworm_node-esm-dirname.patch
* bookworm_node18-import.patch
* bookworm_rust-unsafe-extern.patch
* xtradeb_bindgen-no-c++23.patch
* xtradeb_rust-allocator-types.patch

These patches, that we previously enabled from the Debian patch set,
are also no longer applied thanks to pre-gen:

* bookworm/bindgen.patch
* bookworm/node18-compat.patch
* trixie/bindgen-boringssl.patch
* trixie/node20-compat.patch
* trixie/nodejs-main.patch

While we're at it, drop these patches, as they were applicable to
versions of Rust older than what we're using now (1.91):

* bookworm_derivre-create.patch
* bookworm_rust-visibility.patch
* trixie_adler1.patch
* trixie_rust-is-multiple-of.patch
* xtradeb_rust-alloc-error-handler.patch

These are no longer enabled from Debian, also thanks to 1.91:

* rust-1.85/jxl-features.patch
* rust-1.85/jxl-simd-avx512.patch

Continue to apply these patches, but delete them from our tree,
because they are now included in the Chromium unstable debianization
tarball:

* bookworm_gn-absl.patch
* bookworm_gn-funcs.patch
* trixie_gn-len.patch

script.sh:

* On jammy, don't specify the "-stackclash" build option as it is not
  recognized

* Strip the -fno-stack-clash-protection on all releases after jammy
  (not just noble), as the "arg unused" warning shows up on resolute
  as well

* Disable AVX512 on amd64v3, as skia runs into some non-trivial
  compilation failures like

    FAILED: [code=1] obj/skia/skcms_TransformSkx/skcms_TransformSkx.o
    [...]
    In file included from ../../third_party/skia/modules/skcms/src/skcms_TransformSkx.cc:53:
    ../../third_party/skia/modules/skcms/src/Transform_inl.h:152:15: error: always_inline function '_mm512_cvtph_ps' requires target feature 'avx512f', but would be inlined into function 'F_from_Half' that is compiled without support for 'avx512f'
      152 |     return (F)_mm512_cvtph_ps((__m256i)half);
          |               ^
    ../../third_party/skia/modules/skcms/src/Transform_inl.h:152:15: error: AVX vector return of type '__m512' (vector of 16 'float' values) without 'avx512f' enabled changes the ABI

* Don't apply patches that are obsolete, or now rendered unnecessary

xtradeb_libdav1d-fields.patch: Refresh