chromium: Work around another dependency oversight
This compile error occurs in the ungoogled-chromium build, which is
configured with safe_browsing_mode=0:

FAILED: obj/chrome/browser/ui/views/download/download/download_bubble_contents_view.o
[...]
In file included from ../../chrome/browser/ui/views/download/bubble/download_bubble_contents_view.cc:5:
In file included from ../../chrome/browser/ui/views/download/bubble/download_bubble_contents_view.h:10:
../../chrome/browser/download/download_ui_model.h:23:10: fatal error: 'components/safe_browsing/content/common/proto/download_file_types.pb.h' file not found
   23 | #include "components/safe_browsing/content/common/proto/download_file_types.pb.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Reported upstream at https://issues.chromium.org/397258344 .